intro: "This is a funny app with cats and longer text"
team:
  - {name: "John Capenter", freetext: "Producer"}
  - {name: "Robert Rodriguez", freetext: "visual effects supervisor"}
use_cases:
  - "Modeling"
  - "Down Stream Fishing"
functions:
  - "Test"
  - "Painting"